### ISSUE TITLE
Unable to use the PR's author data in `entry_template`

### ISSUE THREAD

**Issue by slax57** [tf/pr_log#10]
Hi,

First of all, thanks and kudos for this tool, which is the closest I've found so far to the way we'd like to manage the Changelog of our project! 🙏 

Now, when trying to customize the `entry_template` I ran into the following issue: there is apparently no way to use data from nested fields returned by the Github API, in particular the `user` field.

For instance, there is no way to use a template like this: `"- %{title} (#%{number}) by %{user.login}\n"`.

I'm not sure if this should qualify as a bug or an enhancement request, but it's definitely something we'd find useful, and which would make the following sentence (from the Readme) even truer: 

> All fields from the
  [issue search response](https://developer.github.com/v3/search/#search-issues)
  can be used as interpolations.
  
Now, I am by no means a ruby developer, but since we had this need on our project I tried to implement this feature on a forked repository.

I am not sure if my implementation is acceptable or not, since it involves overriding the `%` interpolation operator of the `String` class.
But in case you are interested, you can find it here: https://github.com/slax57/pr_log/pull/1

I'd be happy to open a PR against your repository if you believe my implementation can be kept.

Cheers,

**Comment by tf** [comment]
Hi Jean-Baptiste,

thank you for the kind words! Great to hear you find the tool useful.

I'd be happy to accept a PR to make these types of interpolations work. Just to limit the scope of the change, I'd prefer to have the new interpolation method as a private method of `Formatter` instead of modifying `String`. Other than that your implementation looks fine. Great to see that you also already added a test!

All the best
Tim

**Comment by slax57** [comment]
Thanks for your reply!
As I said I'm not a ruby developer, but I can give it a try anyway.
I'll try to do that in the days to come, and if I succeed, I will open a PR here. :slightly_smiling_face:

**Comment by tf** [comment]
Great. If things do not work out, feel free to open a draft PR and we can have a look together.

**Comment by slax57** [comment]
I've opened a new PR against your repo :slightly_smiling_face: 
I kept the same implementation so it should be good, however I have a warning about the way I handle the `rescue` case, and I must admit I'm not sure what the best practice would be here.
Any advice or commit is welcome :slightly_smiling_face:
