### ISSUE TITLE
Is there any reason to capitalize PR title by default?

### ISSUE THREAD

**Issue by chuganzy** [tf/pr_log#4]
As titled.
https://github.com/tf/pr_log/blob/master/lib/pr_log/formatter.rb#L32

**Comment by tf** [comment]
Yeah, I'd be open to accept a PR that just removes that. Initially thought this might be a good idea to normalize things, but ran into cases myself where camel cased class names etc got messed up.

**Comment by chuganzy** [comment]
Got you! Will make a PR then soon!
